---
version: "2"
services:
  homer:
    image: evervondel/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - /your/local/assets/:/www/assets
      - /your/local/cert/:/cert
    ports:
      - 8080:8080
      - 443:443
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1
      - SSL_ENABLE=0
      - SSL_CERT_NAME=my-cert